

spring.application.name=evoting-system

# Thymeleaf template caching (disable for development)
spring.thymeleaf.cache=false

#configuration za database
spring.datasource.url=jdbc:postgresql://dpg-d82g8inaqgkc7394ptp0-a.oregon-postgres.render.com:5432/evoting_system?user=evoting_system_user&password=DXPfZjqKlLrmhOnY8gxbqUo6HTLQjbDQ&sslmode=require
spring.datasource.username=evoting_system_user
spring.datasource.password=DXPfZjqKlLrmhOnY8gxbqUo6HTLQjbDQ
# jins Hibernate inavyoweza kubadil na kutengeneza tables za databas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration za Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-version=0


#configuration za kuupload file

upload.path=${user.home}/evoting-uploads

#maximam size ya kuupload file ni (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


server.port=${PORT:8080}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gisbertkapinga003@gmail.com
spring.mail.password=ajnidkqkmxddwudu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
